### ISSUE TITLE
Cannot manage to get it to work

### ISSUE THREAD

**Issue by marromlam** [sergei-grechanik/tupimage#4]
I tried cloning your forks of Wezterm and st. But I can't get this script to work:

<img width="579" alt="Screenshot 2024-01-16 at 02 55 08" src="https://github.com/sergei-grechanik/tupimage/assets/41004396/8278afe4-47f5-47c4-8a6e-eb598e098665">

I just see the following in st terminal for example

**Comment by sergei-grechanik** [comment]
Looks like it might be a Unicode issue: as if the diacritics that are supposed to indicate the column are not recognized as diacritics.

Could you try the following things?
- Try displaying an image using `icat-mini.sh` from `st-graphics` (https://github.com/sergei-grechanik/st-graphics/blob/graphics/icat-mini.sh). It's more portable than tupimage, so if it works, it might indicate an issue with bash (if you are using mac os x, it's quite probable).
- Try `cat arrow-up.txt` with this file: [arrow-up.txt](https://github.com/sergei-grechanik/tupimage/files/13944955/arrow-up.txt). It should display a small image of an arrow. If it works, but icat-mini doesn't, then icat-mini is not as portable as I thought.
- If neither of the above works, it may be an issue with st-graphics itself. Try applying this patch to exclude issues with wcwidth: [st-graphics-diacritic-width-experiment.patch.txt](https://github.com/sergei-grechanik/tupimage/files/13945029/st-graphics-diacritic-width-experiment.patch.txt)

**Comment by sergei-grechanik** [comment]
This is an issue with wcwidth on mac os, should be fixed in st-graphics by https://github.com/sergei-grechanik/st-graphics/commit/cc9954ca68c9274f2df8827d5568cad2bb5b4a5a

**Comment by marromlam** [comment]
Thanks! Indeed that commit fixes the issue. It is still not working inside tmux on macOS though
